import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getSortedPostsData, Post } from "../lib/posts";

export default function Home({ allPostsData }: { allPostsData: Array<Post> }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | makim</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicon/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicon/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicon/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicon/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicon/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicon/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/favicon/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicon/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicon/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <div>
        <h1 className="text-3xl">Recent changes</h1>
        <div className="my-6 border-b-2"></div>
        {allPostsData.map((post: Post) => {
          return (
            <div key={post.id} className="pb-14">
              <time dateTime={post.date} className="text-base text-gray-500">
                {post.date}
              </time>
              <h2 className="mt-1 text-2xl">
                <a href={post.slug}>{post.title}</a>
              </h2>
              <div className="mb-2">
                {post.tags?.map((tag) => {
                  return (
                    <span key={tag} className="first:pl-0 pl-2.5">
                      #{tag}
                    </span>
                  );
                })}
              </div>
              <p>{post.description}</p>
            </div>
          );
        })}
        <div className="text-center mb-14">
          <Link href="/pages/1" passHref>
            <button className="w-60 btn-primary">More</button>
          </Link>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsData: Post[] = getSortedPostsData().slice(0, 5);
  return {
    props: {
      allPostsData,
    },
  };
}
